[project]
name = "genoray-cli"
version = "0.2.0"
description = "Command line interface for genoray"
authors = [{ name = "David Laub", email = "dlaub@ucsd.edu" }]
readme = "README.md"
license = { file = "LICENSE" }
requires-python = ">=3.10,<3.14"                              # blocked by cyvcf2
dependencies = ["genoray>=2.1.0", "cyclopts"]

[project.scripts]
genoray = "genoray_cli.__main__:app"

[build-system]
build-backend = "hatchling.build"
requires = ["hatchling"]

[tool.commitizen]
name = "cz_conventional_commits"
tag_format = "$version"
version_scheme = "semver2"
version_provider = "uv"
update_changelog_on_bump = true
major_version_zero = true
